### ISSUE TITLE
Set Up Dashboard

### ISSUE THREAD

**Issue by vaiktorg** [Shehats/Quip#8]
@TannerM504 

You will work on the dashboard since boss (@Shehats)  asked for you to have a lil' experience with them.
Make it so that its ready TO BE connected to the middle end. Set the inputs, the bindings (form stuff).

For the feed area, each post will be its a component so just set up the area so that it inserts a <app-post> tag with the `*ngFor=`

## Bindings and naming.
* For naming the tags (for= & id=) they should be in `camelCase`. 
    * EX: `id="emailInput"` <--- input fields. im not sure if the name attribute is used in angular. Ill get to you unless you find out yourself.
    * `for="emailInput"` <-- is used in label tag.

## Template:
1. Messages Link, 
2. Link to profile, 
3. link to dashboard (from profile), 
4. A thread posting form (text, image uploading)
5.  feed area.

**Comment by TannerM504** [comment]
So you want me to write a bootstrap component to receive information on the client and the posts, and display the posts by himself and his friends on the social network?

**Comment by vaiktorg** [comment]
Just the component with front shit ready for middle-end

**Comment by Shehats** [comment]
Also in the view make all arrays observables of the arrays.
